name = "yourmemory-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "yourmemory"
database_id = "278ed1c5-d78a-4410-ac5e-4dbb48967dc4"
